# Pandas - Python Data Analysis

In [2]:
# import pandas
import pandas as pd

## DataFrame Introduction

In [3]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6,], [7, 8, 9]])
print(f"Size of the dataframe: {df.size}")
print(f"Shape of the dataframe: {df.shape}")
print(f"Top elements of the df:\n {df.head()}")
print(f"Dataframe:\n {df}")

Size of the dataframe: 9
Shape of the dataframe: (3, 3)
Top elements of the df:
    0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
Dataframe:
    0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
# add column names
df = pd.DataFrame([[1, 2, 3], [4, 5, 6,], [7, 8, 9]], columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
# add Row names
df = pd.DataFrame([[1, 2, 3], [4, 5, 6,], [7, 8, 9]], index=[1, 2, 3])
print(df)

   0  1  2
1  1  2  3
2  4  5  6
3  7  8  9

In [6]:
# add column and row names
df = pd.DataFrame([[1, 2, 3], [4, 5, 6,], [7, 8, 9]], columns=['A', 'B', 'C'], index=['1', '2', '3'])
print(df)

   A  B  C
1  1  2  3
2  4  5  6
3  7  8  9

In [7]:
print(f"colums of dataframe: {df.columns}")
print(f"rows of dataframe: {df.index}")

colums of dataframe: Index(['A', 'B', 'C'], dtype='str')
rows of dataframe: Index(['1', '2', '3'], dtype='str')

In [8]:
print(f"unique numbers in each columh: \n{df.nunique()}")
print(f"unique numbers in 'A' column: {df['A'].unique()}")

unique numbers in each columh:
A    3
B    3
C    3
dtype: int64
unique numbers in 'A' column: [1 4 7]

In [9]:
# other useful methods
print(f"DataFrame Info:\n {df.info()}")
print("*-" * 20)
print(f"Stats of dataframe:\n{df.describe()}")

<class 'pandas.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes
DataFrame Info:
 None
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Stats of dataframe:
         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

## Load DataFrame from Files

In [10]:
# load from csv
bios_data = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/master/data/bios.csv')
print(bios_data.head(3)) # use tail() method to list bottom data

   athlete_id                   name   born_date born_city  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux
1           2         Arnaud Boetsch  1969-04-01    Meulan
2           3           Jean Borotra  1898-08-13  Biarritz

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17

In [11]:
# load from feather
results_data = pd.read_feather('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/master/data/results.feather')
print(results_data.head(3))

     year    type discipline                   event                     as  \
0  1912.0  Summer     Tennis  Singles, Men (Olympic)  Jean-François Blanchy
1  1912.0  Summer     Tennis  Doubles, Men (Olympic)  Jean-François Blanchy
2  1920.0  Summer     Tennis  Singles, Men (Olympic)  Jean-François Blanchy

   athlete_id  noc            team  place   tied medal
0           1  FRA             NaN   17.0   True   NaN
1           1  FRA  Jean Montariol    NaN  False   NaN
2           1  FRA             NaN   32.0   True   NaN

In [12]:
# read from parquet - most famous in data analysis because of lightweigth
results_data = pd.read_parquet('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/master/data/results.parquet', engine='pyarrow')
print(results_data.head(2))

     year    type discipline                   event                     as  \
0  1912.0  Summer     Tennis  Singles, Men (Olympic)  Jean-François Blanchy
1  1912.0  Summer     Tennis  Doubles, Men (Olympic)  Jean-François Blanchy

   athlete_id  noc            team  place   tied medal
0           1  FRA             NaN   17.0   True   NaN
1           1  FRA  Jean Montariol    NaN  False   NaN

In [13]:
# read from xlxs
olympics_data = pd.read_excel('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/master/data/olympics-data.xlsx', engine='openpyxl')
print(olympics_data.head(2))

   athlete_id                   name   born_date born_city born_region  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux     Gironde
1           2         Arnaud Boetsch  1969-04-01    Meulan    Yvelines

  born_country     NOC  height_cm  weight_kg   died_date
0          FRA  France        NaN        NaN  1960-10-02
1          FRA  France      183.0       76.0         NaN

## Accessing data with Pandas

In [23]:
# read data from coffee.csv
coffee = pd.read_csv('coffee.csv')
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [15]:
print(f"Top 5 rows: \n {coffee.head(5)}")
print("|+" * 20)
print(f"Last 5 rows: \n {coffee.tail(5)}")
print("|+" * 20)
print(f"Random 5 rows: \n {coffee.sample(5)}")

Top 5 rows:
          Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+
Last 5 rows:
          Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35
|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+
Random 5 rows:
          Day Coffee Type  Units Sold
12    Sunday    Espresso          45
1     Monday       Latte          15
10  Saturday    Espresso          45
3    Tuesday       Latte          20
2    Tuesday    Espresso          30

In [16]:
# using loc[rows, columns] method
# access dataframe using their names

# the stop index is inclusive in loc unlike in iloc
print(f"Units Sold between days 2 to 5: \n{coffee.loc[2:5, 'Units Sold']}")
print("|*" * 20)
print(f"Type of Units Sold between days 2 to 5: \n{coffee.loc[2:5, ['Coffee Type', 'Units Sold']]}")
print("|*" * 20)

Units Sold between days 2 to 5:
2    30
3    20
4    35
5    25
Name: Units Sold, dtype: int64
|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*
Type of Units Sold between days 2 to 5:
  Coffee Type  Units Sold
2    Espresso          30
3       Latte          20
4    Espresso          35
5       Latte          25
|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*

In [17]:
# using iloc[rows, columns] method
# access dataframe using their names

# the stop index is exclusive in iloc unlike in loc
print(f"Units Sold between days 2 to 5: \n{coffee.iloc[2:6, 0:3]}")
print("|*" * 20)
print(f"Type of Units Sold from days 2: \n{coffee.iloc[2:, 1:3]}")
print("|*" * 20)

Units Sold between days 2 to 5:
         Day Coffee Type  Units Sold
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*
Type of Units Sold from days 2:
   Coffee Type  Units Sold
2     Espresso          30
3        Latte          20
4     Espresso          35
5        Latte          25
6     Espresso          40
7        Latte          30
8     Espresso          45
9        Latte          35
10    Espresso          45
11       Latte          35
12    Espresso          45
13       Latte          35
|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*

In [18]:
# modify using loc and iloc
coffee.loc[2, 'Units Sold'] = 25
print(coffee.head(3))

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          25

In [19]:
coffee.iloc[1:3, 1:3] = ['Mocha', 20]
print(coffee.head(4))

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Mocha          20
2  Tuesday       Mocha          20
3  Tuesday       Latte          20

* we can also use .at() and .iat() to access values

In [20]:
# Grab colums
print(f"Coffee Types:\n {coffee["Coffee Type"]}")
print(f"Units Sold:\n {coffee["Units Sold"]}")

Coffee Types:
 0     Espresso
1        Mocha
2        Mocha
3        Latte
4     Espresso
5        Latte
6     Espresso
7        Latte
8     Espresso
9        Latte
10    Espresso
11       Latte
12    Espresso
13       Latte
Name: Coffee Type, dtype: str
Units Sold:
 0     25
1     20
2     20
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

In [21]:
# sort coffee in ascending order
coffee.sort_values('Units Sold', ascending=True)

          Day Coffee Type  Units Sold
1      Monday       Mocha          20
2     Tuesday       Mocha          20
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [22]:
# sort coffee in descending/ascending order based on multiple values
coffee.sort_values(['Units Sold', 'Day'], ascending=[False, True])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
1      Monday       Mocha          20
2     Tuesday       Mocha          20
3     Tuesday       Latte          20

## Filtering

In [24]:
bios_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [25]:
weight_gt_140 = bios_data.loc[bios_data['weight_kg'] > 180, ['name', 'weight_kg']]
print(weight_gt_140)

                  name  weight_kg
59204   Marek Galiński      190.0
60344     Chris Taylor      182.0
105715   Aythami Ruano      198.0

In [26]:
weight_gt_140 = bios_data.loc[(bios_data['weight_kg'] > 180) & (bios_data['height_cm'] > 180), ['name', 'weight_kg', 'height_cm']]
print(weight_gt_140)

                  name  weight_kg  height_cm
59204   Marek Galiński      190.0      200.0
60344     Chris Taylor      182.0      196.0
105715   Aythami Ruano      198.0      200.0

## Adding/Removing Columns

In [27]:
# add price column to coffee
coffee['price'] = 4.99
print(coffee.head())

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [28]:
# add new price column where espresso is 3.99, else 5.99
import numpy as np
coffee['new_price'] = np.where(coffee['Coffee Type'] == "Espresso", 3.99, 5.99)
print(coffee.head())

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          15   4.99       5.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

In [29]:
# use drop method to remove column
coffee.drop(columns=["price"], inplace=True)
print(coffee)

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [30]:
# calculate revenue add it as new column
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']
print(coffee.head(5))

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65

In [31]:
# rename new_price to Price and revenue to Revenue
coffee.rename(columns={'new_price': 'Price', 'revenue': 'Revenue'}, inplace=True)
print(coffee.head(5))

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [32]:
# add column of datetime object
bios_data_new = bios_data.copy()
bios_data_new['datetime'] = pd.to_datetime(bios_data_new['born_date'])
print(bios_data_new.head(3))

   athlete_id                   name   born_date born_city  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux
1           2         Arnaud Boetsch  1969-04-01    Meulan
2           3           Jean Borotra  1898-08-13  Biarritz

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN
1              Yvelines          FRA  France      183.0       76.0
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0

    died_date   datetime
0  1960-10-02 1886-12-12
1         NaN 1969-04-01
2  1994-07-17 1898-08-13

In [33]:
# create csv for bios_data_new
bios_data_new.to_csv('bios_data_new.csv', index=False)

In [34]:
# add heigh category column
bios_data_new['height_cateogry'] = bios_data_new['height_cm'].apply(lambda x: "Short" if x < 165 else "Average" if x < 185 else "Tall")
print(bios_data_new.head(10))

   athlete_id                   name   born_date          born_city  \
0           1  Jean-François Blanchy  1886-12-12           Bordeaux
1           2         Arnaud Boetsch  1969-04-01             Meulan
2           3           Jean Borotra  1898-08-13           Biarritz
3           4        Jacques Brugnon  1895-05-11        Paris VIIIe
4           5           Albert Canet  1878-04-17         Wandsworth
5           6      Nicolas Chatelain  1970-01-13             Amiens
6           7          Patrick Chila  1969-11-27        Ris-Orangis
7           8           Henri Cochet  1901-12-14       Villeurbanne
8           9          Marcel Cousin  1896-08-04              Nîmes
9          10     Guy de la Chapelle  1868-07-16  Farges-Allichamps

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN
1              Yvelines          FRA  France      183.0       76.0
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0
3                 Paris          FRA  France      168.0       64.0
4               England          GBR  France        NaN        NaN
5                 Somme          FRA  France      181.0       70.0
6               Essonne          FRA  France      180.0       73.0
7                 Rhône          FRA  France        NaN        NaN
8                  Gard          FRA  France        NaN        NaN
9                  Cher          FRA  France        NaN        NaN

    died_date   datetime height_cateogry
0  1960-10-02 1886-12-12            Tall
1         NaN 1969-04-01         Average
2  1994-07-17 1898-08-13         Average
3  1978-03-20 1895-05-11         Average
4  1930-07-25 1878-04-17            Tall
5         NaN 1970-01-13         Average
6         NaN 1969-11-27         Average
7  1987-04-02 1901-12-14            Tall
8  1986-08-01 1896-08-04            Tall
9  1923-08-27 1868-07-16            Tall

In [35]:
# categorize athelete
def categorize_athelete(ath):
    if ath['height_cm'] < 175 and ath['weight_kg'] < 70:
        return "Lightweight"
    elif ath['height_cm'] < 185 and ath['weight_kg'] < 85:
        return "Middleweight"
    else:
        return "Heavyweight"

bios_data_new['category'] = bios_data_new.apply(categorize_athelete, axis=1)
print(bios_data_new.head(5))

   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN
1              Yvelines          FRA  France      183.0       76.0
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0
3                 Paris          FRA  France      168.0       64.0
4               England          GBR  France        NaN        NaN

    died_date   datetime height_cateogry      category
0  1960-10-02 1886-12-12            Tall   Heavyweight
1         NaN 1969-04-01         Average  Middleweight
2  1994-07-17 1898-08-13         Average  Middleweight
3  1978-03-20 1895-05-11         Average   Lightweight
4  1930-07-25 1878-04-17            Tall   Heavyweight

## Merging andConcatenating Data

In [37]:
# importing noc file from kaggle dataset
# import kagglehub

# path = kagglehub.dataset_download("heesoo37/120-years-of-olympic-history-athletes-and-results")

# print(path)

In [38]:
# read noc regions
noc = pd.read_csv('noc_regions.csv')
print(noc.head(5))

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [39]:
# merge bios_data and noc
bios_new = pd.merge(bios_data, noc, left_on="born_country", right_on="NOC", how="left")
print(bios_new.head(2))

   athlete_id                   name   born_date born_city born_region  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux     Gironde
1           2         Arnaud Boetsch  1969-04-01    Meulan    Yvelines

  born_country   NOC_x  height_cm  weight_kg   died_date NOC_y  region notes
0          FRA  France        NaN        NaN  1960-10-02   FRA  France   NaN
1          FRA  France      183.0       76.0         NaN   FRA  France   NaN

In [40]:
bios_new.rename(columns={"region": "born_country_full"}, inplace=True)
print(bios_new.head(5))

   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country   NOC_x  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN
1              Yvelines          FRA  France      183.0       76.0
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0
3                 Paris          FRA  France      168.0       64.0
4               England          GBR  France        NaN        NaN

    died_date NOC_y born_country_full notes
0  1960-10-02   FRA            France   NaN
1         NaN   FRA            France   NaN
2  1994-07-17   FRA            France   NaN
3  1978-03-20   FRA            France   NaN
4  1930-07-25   GBR                UK   NaN

In [41]:
# list people playing for country which is not their Place of birth
bios_new[bios_new["NOC_x"] != bios_new["born_country_full"]][['name', 'NOC_x', 'born_country_full']].head(5)

                  name   NOC_x born_country_full
4         Albert Canet  France                UK
12           J. Defert  France               NaN
13      Étienne Durand  France               NaN
16          Guy Forget  France           Morocco
27  Guy, Baron Lejeune  France               NaN

In [42]:
# retrieve indian olympians
indians = bios_data[bios_data['NOC'] == "India"]
display(indians.tail(5))

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
144065,147731,Reena Khokhar,1993-04-10,NaN,NaN,NaN,India,NaN,NaN,NaN
144097,147765,Simranjeet Singh,1996-12-27,NaN,NaN,NaN,India,NaN,NaN,NaN
144098,147766,Varun Kumar,1995-07-25,NaN,NaN,NaN,India,NaN,NaN,NaN
144114,147784,Diksha Dagar,2000-12-14,Jhajjar,Haryana,IND,India,174.0,NaN,NaN
144757,148458,Arif Khan,1990-03-09,Gulmarg,Jammu and Kashmir,IND,India,NaN,NaN,NaN

In [43]:
# retrieve pakistani olympians
pakistanis = bios_data[bios_data['NOC'] == "Pakistan"]
display(pakistanis.tail(5))

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
142241,145843,Arshad Nadeem,1997-01-02,NaN,NaN,NaN,Pakistan,NaN,NaN,NaN
142242,145844,Gulfam Joseph,1999-12-17,NaN,NaN,NaN,Pakistan,178.0,NaN,NaN
142243,145845,Muhammad Khalil Akhtar,1984-04-15,NaN,NaN,NaN,Pakistan,167.0,NaN,NaN
142244,145846,Syed Muhammad Haseeb Tariq,1996-04-06,NaN,NaN,NaN,Pakistan,NaN,NaN,NaN
142245,145847,Talha Talib,1999-10-03,Gujranwala,Punjab,PAK,Pakistan,172.0,67.0,NaN

In [44]:
ind_vs_pak = pd.concat([indians, pakistanis])
display(ind_vs_pak.head(5))

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
269,270,Madhumita Bisht,1964-10-05,NaN,NaN,NaN,India,NaN,NaN,NaN
270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01
271,272,Ambika Radhika,1973-05-17,NaN,NaN,NaN,India,NaN,NaN,NaN
272,273,Niyati Roy-Shah,1965-09-30,NaN,NaN,NaN,India,NaN,NaN,NaN
273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN

## Handling NaN values

In [45]:
# add NaN values to some in coffee
coffee.loc[[2, 3], 'Units Sold'] = np.nan
display(coffee)

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso        25.0   3.99    99.75
1      Monday       Latte        15.0   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [46]:
# check NaN count in each column
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
Price          0
Revenue        0
dtype: int64

In [47]:
# interpolate NaN
coffee["Units Sold"] = coffee["Units Sold"].interpolate()
display(coffee)

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso   25.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

## Aggregating Data

In [56]:
# each county olympian count
bios_data["born_country"].value_counts()

born_country
USA       9641
GER       6891
GBR       5792
FRA       5143
ITA       4709
          ...
Havel        1
SMT          1
COK          1
Corfu        1
Aarhus       1
Name: count, Length: 236, dtype: int64

In [57]:
# get people from india
bios_data[bios_data['NOC'] == "India"]["born_region"].value_counts().head(7)

born_region
Punjab           82
Haryana          41
Maharashtra      39
Uttar Pradesh    36
West Bengal      32
Karnataka        28
Tamil Nadu       25
Name: count, dtype: int64

In [58]:
display(coffee)

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso   25.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [59]:
print(f"Average Units Sold by each type:\n{coffee.groupby(["Coffee Type"])["Units Sold"].mean()}")
print(f"Average cost by each type:\n{coffee.groupby(["Coffee Type"])["Price"].mean()}")
print(f"Total revenue by each type:\n{coffee.groupby(["Coffee Type"])["Revenue"].sum()}")

Average Units Sold by each type:
Coffee Type
Espresso    36.666667
Latte       29.047619
Name: Units Sold, dtype: float64
Average cost by each type:
Coffee Type
Espresso    3.99
Latte       5.99
Name: Price, dtype: float64
Total revenue by each type:
Coffee Type
Espresso    1057.35
Latte       1168.05
Name: Revenue, dtype: float64

In [60]:
# using agg
coffee.groupby(["Coffee Type"]).agg({"Units Sold": "sum", "Price": "mean", "Revenue": "sum"})

             Units Sold  Price  Revenue
Coffee Type
Espresso     256.666667   3.99  1057.35
Latte        203.333333   5.99  1168.05

In [61]:
# pivoting technique
pivot = coffee.pivot(columns="Coffee Type", index="Day", values="Revenue") # values = "Units Sold"
display(pivot)

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [62]:
pivot.sum(axis=1) # each day revenue from all coffee types

Day
Friday       389.2
Monday       189.6
Saturday     389.2
Sunday       389.2
Thursday     339.3
Tuesday      239.5
Wednesday    289.4
dtype: float64

In [63]:
coffee

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso   25.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

## Advanced Functionality

In [65]:
# shift method to get yesterday revenue
coffee["Yesterday Revenue"] = coffee["Revenue"].shift(2)
display(coffee.head(5))

         Day Coffee Type  Units Sold  Price  Revenue  Yesterday Revenue
0     Monday    Espresso   25.000000   3.99    99.75                NaN
1     Monday       Latte   15.000000   5.99    89.85                NaN
2    Tuesday    Espresso   21.666667   3.99   119.70              99.75
3    Tuesday       Latte   28.333333   5.99   119.80              89.85
4  Wednesday    Espresso   35.000000   3.99   139.65             119.70

In [69]:
coffee["Pct Change"] = coffee["Revenue"] / coffee["Yesterday Revenue"] * 100
display(coffee.head(5))

,Day,Coffee Type,Units Sold,Price,Revenue,Yesterday Revenue,Pct Change
0,Monday,Espresso,25.000000,3.99,99.75,NaN,NaN
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,21.666667,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667

In [71]:
# use rank function
bios_data["height_rank"] = bios_data["height_cm"].rank(ascending=False)
display(bios_data.sort_values("height_rank").head(5))

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,1.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,2.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,2.5
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN,5.0
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,5.0

In [73]:
# use cumsum method to get cumulative revenue
coffee["Cumulative Revenue"] = coffee["Revenue"].cumsum()
display(coffee)

,Day,Coffee Type,Units Sold,Price,Revenue,Yesterday Revenue,Pct Change,Cumulative Revenue
0,Monday,Espresso,25.000000,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.60
2,Tuesday,Espresso,21.666667,3.99,119.70,99.75,120.000000,309.30
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333,429.10
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667,568.75
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.50
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714,878.10
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.80
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000,1237.35
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.00
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000,1626.55
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.20
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000,2015.75
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.40

In [77]:
# using rolling function to have 3 day units sold for latte
latte = coffee[coffee["Coffee Type"] == "Latte"].copy()
latte["3day US"] = latte["Units Sold"].rolling(3).sum()
display(latte)

,Day,Coffee Type,Units Sold,Price,Revenue,Yesterday Revenue,Pct Change,Cumulative Revenue,3day US
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.6,NaN
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333,429.1,NaN
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.5,68.333333
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.8,83.333333
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.0,90.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.2,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.4,105.000000